// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApplicationBackEnd.Models;

namespace StudentApplicationBackEnd.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentApplicationBackEnd.Models.tbl_Mark", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("StudentMark")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK_tbl_Marks");

                    b.HasIndex("StudentID");

                    b.ToTable("tbl_Marks");
                });

            modelBuilder.Entity("StudentApplicationBackEnd.Models.tbl_Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("ID")
                        .HasName("PK_tbl_Students");

                    b.ToTable("tbl_Students");
                });

            modelBuilder.Entity("StudentApplicationBackEnd.Models.tbl_Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID")
                        .HasName("PK_tbl_Subjects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("IDX_tbl_Subjects_Name");

                    b.ToTable("tbl_Subjects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Math"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Physics"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Chemistry"
                        });
                });

            modelBuilder.Entity("StudentApplicationBackEnd.Models.tbl_Mark", b =>
                {
                    b.HasOne("StudentApplicationBackEnd.Models.tbl_Student", "tbl_Student")
                        .WithMany("tbl_Marks")
                        .HasForeignKey("StudentID")
                        .HasConstraintName("FK_tbl_Students_tbl_Marks")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentApplicationBackEnd.Models.tbl_Subject", "tbl_Subject")
                        .WithMany("tbl_Marks")
                        .HasForeignKey("StudentID")
                        .HasConstraintName("FK_tbl_Subjects_tbl_Marks")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
